(function(){
  const messages={
    ru:{
      home:'В начало',archiveCount:'записей в архиве',signIn:'Войти',signOut:'Выйти',heroIntro:'Фильмы и сериалы, которые оставили свой кадр в памяти. Открывай карточку — внутри описание, режиссёр, оценка и трейлер.',viewCollection:'Смотреть коллекцию',collectionStats:'Статистика коллекции',movies:'фильмов',series:'сериала',rated:'оценено',catalog:'КАТАЛОГ',watched:'Просмотренное',searchLabel:'Найти фильм или сериал',searchPlaceholder:'Найти в архиве…',type:'Тип',all:'все',films:'фильмы',shows:'сериалы',genre:'Жанр',allGenres:'все жанры',director:'Режиссёр',allDirectors:'все режиссёры',sorting:'Сортировка',alphabetical:'по алфавиту',byImdb:'по оценке IMDb',direction:'Направление',descending:'по убыванию',ascending:'по возрастанию',emptyFilm:'ПЛЁНКА ПУСТА',nothingFound:'Ничего не найдено',emptyHelp:'Попробуй изменить запрос или выбрать другой фильтр.',resetFilters:'Сбросить фильтры',close:'Закрыть',personalRating:'ЛИЧНАЯ ОЦЕНКА',howWasIt:'Как тебе это кино?',removeRating:'Удалить оценку',loadingDetails:'Загружаю описание и обложку…',watchTrailer:'Смотреть трейлер',rate:'Поставить оценку',trailerNote:'Трейлер откроется в поиске YouTube — так всегда найдётся актуальная официальная версия.',continued:'Продолжение следует ···',shown:'Показано {shown} из {total}',openFilm:'Открыть страницу фильма: {title}',cover:'Обложка — {title}',coverLoading:'Загрузка обложки',movie:'Фильм',show:'Сериал',ratingsCount:'{count} оценок',noRatings:'нет оценок',openPage:'Открыть страницу',imdbLoading:'IMDb · загрузка {done}/{total}',descriptionSoon:'Описание этого фильма скоро появится в архиве.',descriptionError:'Описание пока не загрузилось. Проверь подключение к интернету.',myRating:'Моя оценка: {rating}/10',
      back:'← Назад к коллекции',filmPageTitle:'VERBTW FILMS — фильм',posterLoading:'Загрузка обложки…',collectionLabel:'КОЛЛЕКЦИЯ VERBTW',loading:'Загрузка…',description:'Описание',loadingDescription:'Загружаю описание фильма…',trailer:'Трейлер',trailerPreview:'Наведи курсор, чтобы посмотреть трейлер',hoverTrailer:'Наведи, чтобы посмотреть',trailerInline:'Трейлер запустится без перехода с сайта',searchingTrailer:'Ищу трейлер…',audienceRatings:'Оценки зрителей',communityRating:'VERBTW RATING',noRatingsYet:'Пока нет оценок',myScore:'Моя оценка',signInToRate:'Войди в аккаунт, чтобы оценка сохранилась на всех устройствах.',ratingSaved:'Оценка сохранится в твоём аккаунте.',directorLoading:'Режиссёр загружается',directorMissing:'Режиссёр не указан',trailerNotFound:'Трейлер не найден',descriptionLoadError:'Описание не загрузилось. Проверь подключение к интернету и обнови страницу.',
      community:'VERBTW COMMUNITY',authTitle:'Войти',authLead:'Твои оценки сохранятся в аккаунте.',nickname:'Ник',email:'Почта',password:'Пароль',createAccount:'Создать аккаунт',register:'Зарегистрироваться',haveAccount:'У меня уже есть аккаунт',registerLead:'Оценивай фильмы и сохраняй историю.',checkEmail:'Проверь почту и подтверди регистрацию.',comingSoon:'Регистрация скоро заработает.',nicknameError:'Укажи ник минимум из двух символов.',authError:'Не удалось выполнить вход.',signInSave:'Войди, чтобы оценка сохранилась в профиле.',signInOrCreate:'Войди или создай аккаунт, чтобы сохранить оценку.',profile:'Профиль',metaDescription:'Личная коллекция просмотренных фильмов и сериалов VERBTW'
    },
    en:{
      home:'Back to top',archiveCount:'titles in the archive',signIn:'Sign in',signOut:'Sign out',heroIntro:'Films and series that left a frame in memory. Open a card for the story, director, rating and trailer.',viewCollection:'View collection',collectionStats:'Collection statistics',movies:'films',series:'series',rated:'rated',catalog:'CATALOG',watched:'Watched',searchLabel:'Find a film or series',searchPlaceholder:'Search the archive…',type:'Type',all:'all',films:'films',shows:'series',genre:'Genre',allGenres:'all genres',director:'Director',allDirectors:'all directors',sorting:'Sort by',alphabetical:'alphabetical',byImdb:'IMDb rating',direction:'Direction',descending:'high to low',ascending:'low to high',emptyFilm:'NO FRAMES FOUND',nothingFound:'Nothing found',emptyHelp:'Try another search or change the filters.',resetFilters:'Reset filters',close:'Close',personalRating:'MY RATING',howWasIt:'How did you like it?',removeRating:'Remove rating',loadingDetails:'Loading description and poster…',watchTrailer:'Watch trailer',rate:'Rate this title',trailerNote:'The trailer opens in YouTube search so the latest official version is always available.',continued:'To be continued ···',shown:'Showing {shown} of {total}',openFilm:'Open film page: {title}',cover:'Poster — {title}',coverLoading:'Loading poster',movie:'Film',show:'Series',ratingsCount:'{count} ratings',noRatings:'no ratings',openPage:'Open page',imdbLoading:'IMDb · loading {done}/{total}',descriptionSoon:'A description for this title is coming soon.',descriptionError:'The description could not be loaded. Check your connection.',myRating:'My rating: {rating}/10',
      back:'← Back to collection',filmPageTitle:'VERBTW FILMS — film',posterLoading:'Loading poster…',collectionLabel:'VERBTW COLLECTION',loading:'Loading…',description:'Description',loadingDescription:'Loading film description…',trailer:'Trailer',trailerPreview:'Hover to watch the trailer',hoverTrailer:'Hover to watch',trailerInline:'The trailer plays without leaving the site',searchingTrailer:'Finding trailer…',audienceRatings:'Audience ratings',communityRating:'VERBTW RATING',noRatingsYet:'No ratings yet',myScore:'My rating',signInToRate:'Sign in to keep your rating on every device.',ratingSaved:'Your rating is saved to your account.',directorLoading:'Loading director',directorMissing:'Director unavailable',trailerNotFound:'Trailer not found',descriptionLoadError:'The description could not be loaded. Check your connection and refresh the page.',
      community:'VERBTW COMMUNITY',authTitle:'Sign in',authLead:'Your ratings are saved to your account.',nickname:'Display name',email:'Email',password:'Password',createAccount:'Create account',register:'Create account',haveAccount:'I already have an account',registerLead:'Rate films and keep your history.',checkEmail:'Check your email to confirm registration.',comingSoon:'Registration will be available soon.',nicknameError:'Enter a display name with at least two characters.',authError:'Could not sign in.',signInSave:'Sign in to save this rating to your profile.',signInOrCreate:'Sign in or create an account to save your rating.',profile:'Profile',metaDescription:'VERBTW’s personal collection of watched films and series'
    }
  };
  let language=localStorage.getItem('verbtw-language')==='en'?'en':'ru';
  function t(key,values={}){let value=messages[language][key]||messages.ru[key]||key;return Object.entries(values).reduce((text,[name,replacement])=>text.replaceAll(`{${name}}`,replacement),value);}
  function apply(root=document){
    document.documentElement.lang=language;
    root.querySelectorAll('[data-i18n]').forEach(element=>element.textContent=t(element.dataset.i18n));
    root.querySelectorAll('[data-i18n-placeholder]').forEach(element=>element.placeholder=t(element.dataset.i18nPlaceholder));
    root.querySelectorAll('[data-i18n-aria]').forEach(element=>element.setAttribute('aria-label',t(element.dataset.i18nAria)));
    root.querySelectorAll('[data-i18n-content]').forEach(element=>element.setAttribute('content',t(element.dataset.i18nContent)));
    document.querySelectorAll('[data-language]').forEach(button=>{const active=button.dataset.language===language;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});
  }
  function setLanguage(next){if(!messages[next]||next===language)return;language=next;localStorage.setItem('verbtw-language',language);apply();window.dispatchEvent(new CustomEvent('languagechange',{detail:{language}}));}
  document.addEventListener('click',event=>{const button=event.target.closest('[data-language]');if(button)setLanguage(button.dataset.language);});
  window.i18n={t,apply,setLanguage,get language(){return language;}};
})();
